const data = [
  {
    name: `Dearest king`,
    price: '1MBT',
    distance: '2345km',
    duration: 'available for 2weeks stay',
    image: `../public/images/image_1.png`,
    rating: [
      '../public/images/star-1.png',
      '../public/images/star-1.png',
      '../public/images/star-1.png',
      '../public/images/star-1.png',
      '../public/images/star-1.png',
    ],
  },
  {
    name: 'Dearest king',
    price: '1MBT',
    distance: '2345km',
    duration: 'available for 2weeks stay',
    image: '../public/images/image_2.png',
    rating: [
      '../public/images/star-1.png',
      '../public/images/star-1.png',
      '../public/images/star-1.png',
      '../public/images/star-1.png',
      '../public/images/star-1.png',
    ],
  },
  {
    name: 'Dearest king',
    price: '1MBT',
    distance: '2345km',
    duration: 'available for 2weeks stay',
    image: './images/image_3.png',
    rating: [
      './images/star-1.png',
      '../public/images/star-1.png',
      '../public/images/star-1.png',
      '../public/images/star-1.png',
      '../public/images/star-1.png',
    ],
  },
  {
    name: 'Dearest king',
    price: '1MBT',
    distance: '2345km',
    duration: 'available for 2weeks stay',
    image: '../public/images/image_4.png',
    rating: [
      '../public/images/star-1.png',
      '../public/images/star-1.png',
      '../public/images/star-1.png',
      '../public/images/star-1.png',
      '../public/images/star-1.png',
    ],
  },
  {
    name: 'Dearest king',
    price: '1MBT',
    distance: '2345km',
    duration: 'available for 2weeks stay',
    image: '../public/images/image_5.png',
    rating: [
      '../public/images/star-1.png',
      '../public/images/star-1.png',
      '../public/images/star-1.png',
      '../public/images/star-1.png',
      '../public/images/star-1.png',
    ],
  },
  {
    name: 'Dearest king',
    price: '1MBT',
    distance: '2345km',
    duration: 'available for 2weeks stay',
    image: '../public/images/image_6.png',
    rating: [
      '../public/images/star-1.png',
      '../public/images/star-1.png',
      '../public/images/star-1.png',
      '../public/images/star-1.png',
      '../public/images/star-1.png',
    ],
  },
  {
    name: 'Dearest king',
    price: '1MBT',
    distance: '2345km',
    duration: 'available for 2weeks stay',
    image: '../public/images/image_7.png',
    rating: [
      '../public/images/star-1.png',
      '../public/images/star-1.png',
      '../public/images/star-1.png',
      '../public/images/star-1.png',
      '../public/images/star-1.png',
    ],
  },
  {
    name: 'Dearest king',
    price: '1MBT',
    distance: '2345km',
    duration: 'available for 2weeks stay',
    image: '../public/images/image_8.png',
    rating: [
      '../public/images/star-1.png',
      '../public/images/star-1.png',
      '../public/images/star-1.png',
      '../public/images/star-1.png',
      '../public/images/star-1.png',
    ],
  },
]
export default data
