export const links = [
  { id: 1, text: 'Home', url: '/' },
  { id: 2, text: 'Place to stay', url: '/place' },
  { id: 3, text: 'NFTs', url: '#' },
  { id: 4, text: 'Community', url: '#' },
]

export const metaData = [
  {
    name: 'Dearest king',
    price: '1MBT',
    distance: '2345km',
    duration: 'available for 2weeks stay',
    image: '/images/image_1.png',
    rating: [
      '/images/star-1.png',
      '/images/star-1.png',
      '/images/star-1.png',
      '/images/star-1.png',
      '/images/star-1.png',
    ],
  },
  {
    name: 'Dearest king',
    price: '1MBT',
    distance: '2345km',
    duration: 'available for 2weeks stay',
    image: '/images/image_2.png',
    rating: [
      '/images/star-1.png',
      '/images/star-1.png',
      '/images/star-1.png',
      '/images/star-1.png',
      '/images/star-1.png',
    ],
  },
  {
    name: 'Dearest king',
    price: '1MBT',
    distance: '2345km',
    duration: 'available for 2weeks stay',
    image: '/images/image_3.png',
    rating: [
      '/images/star-1.png',
      '/images/star-1.png',
      '/images/star-1.png',
      '/images/star-1.png',
      '/images/star-1.png',
    ],
  },
  {
    name: 'Dearest king',
    price: '1MBT',
    distance: '2345km',
    duration: 'available for 2weeks stay',
    image: '/images/image_4.png',
    rating: [
      '/images/star-1.png',
      '/images/star-1.png',
      '/images/star-1.png',
      '/images/star-1.png',
      '/images/star-1.png',
    ],
  },
  {
    name: 'Dearest king',
    price: '1MBT',
    distance: '2345km',
    duration: 'available for 2weeks stay',
    image: '/images/image_5.png',
    rating: [
      '/images/star-1.png',
      '/images/star-1.png',
      '/images/star-1.png',
      '/images/star-1.png',
      '/images/star-1.png',
    ],
  },
  {
    name: 'Dearest king',
    price: '1MBT',
    distance: '2345km',
    duration: 'available for 2weeks stay',
    image: '/images/image_6.png',
    rating: [
      '/images/star-1.png',
      '/images/star-1.png',
      '/images/star-1.png',
      '/images/star-1.png',
      '/images/star-1.png',
    ],
  },
  {
    name: 'Dearest king',
    price: '1MBT',
    distance: '2345km',
    duration: 'available for 2weeks stay',
    image: '/images/image_7.png',
    rating: [
      '/images/star-1.png',
      '/images/star-1.png',
      '/images/star-1.png',
      '/images/star-1.png',
      '/images/star-1.png',
    ],
  },
  {
    name: 'Dearest king',
    price: '1MBT',
    distance: '2345km',
    duration: 'available for 2weeks stay',
    image: '/images/image_8.png',
    rating: [
      '/images/star-1.png',
      '/images/star-1.png',
      '/images/star-1.png',
      '/images/star-1.png',
      '/images/star-1.png',
    ],
  },
]

export const placeData = [
  {
    name: 'Dearest king',
    price: '1MBT',
    distance: '2345km',
    duration: 'available for 2weeks stay',
    image: '/img-folder/image_1.png',
    rating: [
      '/images/star-1.png',
      '/images/star-1.png',
      '/images/star-1.png',
      '/images/star-1.png',
      '/images/star-1.png',
    ],
  },
  {
    name: 'Dearest king',
    price: '1MBT',
    distance: '2345km',
    duration: 'available for 2weeks stay',
    image: '/img-folder/image_2.png',
    rating: [
      '/images/star-1.png',
      '/images/star-1.png',
      '/images/star-1.png',
      '/images/star-1.png',
      '/images/star-1.png',
    ],
  },
  {
    name: 'Dearest king',
    price: '1MBT',
    distance: '2345km',
    duration: 'available for 2weeks stay',
    image: '/img-folder/image_3.png',
    rating: [
      '/images/star-1.png',
      '/images/star-1.png',
      '/images/star-1.png',
      '/images/star-1.png',
      '/images/star-1.png',
    ],
  },
  {
    name: 'Dearest king',
    price: '1MBT',
    distance: '2345km',
    duration: 'available for 2weeks stay',
    image: '/img-folder/image_4.png',
    rating: [
      '/images/star-1.png',
      '/images/star-1.png',
      '/images/star-1.png',
      '/images/star-1.png',
      '/images/star-1.png',
    ],
  },
  {
    name: 'Dearest king',
    price: '1MBT',
    distance: '2345km',
    duration: 'available for 2weeks stay',
    image: '/img-folder/image_5.png',
    rating: [
      '/images/star-1.png',
      '/images/star-1.png',
      '/images/star-1.png',
      '/images/star-1.png',
      '/images/star-1.png',
    ],
  },
  {
    name: 'Dearest king',
    price: '1MBT',
    distance: '2345km',
    duration: 'available for 2weeks stay',
    image: '/img-folder/image_6.png',
    rating: [
      '/images/star-1.png',
      '/images/star-1.png',
      '/images/star-1.png',
      '/images/star-1.png',
      '/images/star-1.png',
    ],
  },
  {
    name: 'Dearest king',
    price: '1MBT',
    distance: '2345km',
    duration: 'available for 2weeks stay',
    image: '/img-folder/image_7.png',
    rating: [
      '/images/star-1.png',
      '/images/star-1.png',
      '/images/star-1.png',
      '/images/star-1.png',
      '/images/star-1.png',
    ],
  },
  {
    name: 'Dearest king',
    price: '1MBT',
    distance: '2345km',
    duration: 'available for 2weeks stay',
    image: '/img-folder/image_8.png',
    rating: [
      '/images/star-1.png',
      '/images/star-1.png',
      '/images/star-1.png',
      '/images/star-1.png',
      '/images/star-1.png',
    ],
  },
  {
    name: 'Dearest king',
    price: '1MBT',
    distance: '2345km',
    duration: 'available for 2weeks stay',
    image: '/img-folder/image_9.png',
    rating: [
      '/images/star-1.png',
      '/images/star-1.png',
      '/images/star-1.png',
      '/images/star-1.png',
      '/images/star-1.png',
    ],
  },
  {
    name: 'Dearest king',
    price: '1MBT',
    distance: '2345km',
    duration: 'available for 2weeks stay',
    image: '/img-folder/image_10.png',
    rating: [
      '/images/star-1.png',
      '/images/star-1.png',
      '/images/star-1.png',
      '/images/star-1.png',
      '/images/star-1.png',
    ],
  },
  {
    name: 'Dearest king',
    price: '1MBT',
    distance: '2345km',
    duration: 'available for 2weeks stay',
    image: '/img-folder/image_11.png',
    rating: [
      '/images/star-1.png',
      '/images/star-1.png',
      '/images/star-1.png',
      '/images/star-1.png',
      '/images/star-1.png',
    ],
  },
  {
    name: 'Dearest king',
    price: '1MBT',
    distance: '2345km',
    duration: 'available for 2weeks stay',
    image: '/img-folder/image_12.png',
    rating: [
      '/images/star-1.png',
      '/images/star-1.png',
      '/images/star-1.png',
      '/images/star-1.png',
      '/images/star-1.png',
    ],
  },
  {
    name: 'Dearest king',
    price: '1MBT',
    distance: '2345km',
    duration: 'available for 2weeks stay',
    image: '/img-folder/image_13.png',
    rating: [
      '/images/star-1.png',
      '/images/star-1.png',
      '/images/star-1.png',
      '/images/star-1.png',
      '/images/star-1.png',
    ],
  },
  {
    name: 'Dearest king',
    price: '1MBT',
    distance: '2345km',
    duration: 'available for 2weeks stay',
    image: '/img-folder/image_14.png',
    rating: [
      '/images/star-1.png',
      '/images/star-1.png',
      '/images/star-1.png',
      '/images/star-1.png',
      '/images/star-1.png',
    ],
  },
  {
    name: 'Dearest king',
    price: '1MBT',
    distance: '2345km',
    duration: 'available for 2weeks stay',
    image: '/img-folder/image_15.png',
    rating: [
      '/images/star-1.png',
      '/images/star-1.png',
      '/images/star-1.png',
      '/images/star-1.png',
      '/images/star-1.png',
    ],
  },
  {
    name: 'Dearest king',
    price: '1MBT',
    distance: '2345km',
    duration: 'available for 2weeks stay',
    image: '/img-folder/image_16.png',
    rating: [
      '/images/star-1.png',
      '/images/star-1.png',
      '/images/star-1.png',
      '/images/star-1.png',
      '/images/star-1.png',
    ],
  },
]
